name: GitHub Activity Readme

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repository's README.md with recent user activity

    steps:
      - uses: actions/checkout@v2
      - uses: rivenirvana/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: ':zap: Update README with the recent activity'
          MAX_LINES: 10
